### ISSUE TITLE
Code Bug

### ISSUE THREAD

**Issue by NonstickAtom785** [Zeda/Grammer2#13]
Still having an issue with getting the size of the program. It's definitely not a misuse of the syntax as I used your method of `{Z-2->K` to get the size but when I execute it(with the program I put on discord) it doesn't crash it just create one of those `u` vars and when I delete that I get `Y1` with a huge size. The `u` var is fairly small btw, in case that leads to anything for you. I'm using that code to make the example Match game.

**Comment by Zeda** [comment]
What does your `Z` point to?

**EDIT:** To clarify, the code I gave you for the `{Z-2` was assuming that you had created an OS var, since you used the `length(` command and that Z pointed to the start of the var's data. The OS prefixes the data with a 16-bit size byte. However, the shuffle code example I made has the array at `0x9872`, not in an OS var; it doesn't hold any information about its length; that's the program's job.

**Comment by NonstickAtom785** [comment]
Hmm I made my array in an Appvar. Here's the entire code block so you can see if I am using the correct syntax.
```
.0:Return
MakeVar(16,"UMatch→Z
For K,1,16
WriteB(Z+K,K
End
Call Lbl "SHUFFLE
ClrDraw
.I did this to make sure that it was giving me a random list between 1 and 16
For F,1,16
Text('°(Z+F
Text(°" 
End
DispGraph
Stop
.SHUFFLE
{Z-2→K
While K>1
randInt(1,K→A
(Z+K→B
WriteB(Z+K,(Z+A
WriteB(Z+A,B
K-1→K
End
End
```

**Comment by Zeda** [comment]
Indices start at 0, not 1. Your initialization loop and shuffle loop are writing up to 1 byte *after* the data, which is usually a size byte of a `Y=` var.
For the initializing, loop from 0 to 15 and in the shuffling, with the way you are doing it, move the `K-1` to the start of the while loop and check that `K>2`.

**Comment by NonstickAtom785** [comment]
Okay sounds good. Didn't realize that I had to start with 0. I'll give it a try with your fix and starting with 0 and report back.

**Comment by NonstickAtom785** [comment]
Well starting at 0 still gives me the variable issue. And so does putting the K-1 at the beginning of the while loop.
Both codes:
### K-1 at the beginning code:
```
.0:Return
MakeVar(16,"UMatch→Z
For K,1,16
WriteB(Z+K,K
End
Call Lbl "SHUFFLE
ClrDraw
.I did this to make sure that it was giving me a random list between 1 and 16
For F,1,16
Text('°(Z+F
Text(°" 
End
DispGraph
Stop
.SHUFFLE
{Z-2→K
While K>2
K-1→K
randInt(1,K→A
(Z+K→B
WriteB(Z+K,(Z+A
WriteB(Z+A,B
End
End
```
### 0 Code:
```.0:Return
MakeVar(16,"UMatch→Z
For K,0,15
WriteB(Z+K,K
End
Call Lbl "SHUFFLE
ClrDraw
.I did this to make sure that it was giving me a random list between 1 and 16
For F,0,15
Text('°(Z+F
Text(°" 
End
DispGraph
Stop
.SHUFFLE
{Z-2→K
While K>1
randInt(1,K→A
(Z+K→B
WriteB(Z+K,(Z+A
WriteB(Z+A,B
K-1→K
End
End
```

**Comment by Zeda** [comment]
You need to do both.

**Comment by NonstickAtom785** [comment]
Well combined it doesn't shuffle the deck. :/
Never mind. I had `{Z-1->K` instead of `{Z-2->K`.
Here's the updated code for anyone who might be looking at the old issues.
```
MakeVar(16,"UMatch→Z
For K,0,15
WriteB(Z+K,K
End
Call Lbl "SHUFFLE
ClrDraw
.I did this to make sure that it was giving me a random list between 1 and 16
For F,0,15
Text('°(Z+F
Text(°" 
End
DispGraph
Stop
.SHUFFLE
{Z-2→K
While K>2
K-1→K
randInt(0,K→A
(Z+K→B
WriteB(Z+K,(Z+A
WriteB(Z+A,B
End
End
```
