### ISSUE TITLE
Need to mention that Lbl pointers can change causing crashes.

### ISSUE THREAD

**Issue by Zeda** [Zeda/Grammer2#16]
From Hans Burch:

> There needs to be mentioned, that there will be crashes, when the program shifts in RAM, because of changing OS-vars, and having pointers to Lbls and others.

While it doesn't always crash (often it errors), it _can_ crash and users need to be aware of this!

**Comment by NonstickAtom785** [comment]
I had an error a little bit ago that cause the program to get stuck where it was at either in RAM or Archive. I could un-archive/archive it period.

**Comment by Zeda** [comment]
I added the note to the `Lbl` routine documentation!
