### ISSUE TITLE
Storing to lowercase pvars is broken.

### ISSUE THREAD

**Issue by Zeda** [Zeda/Grammer2#18]
(via Hans)
It seems, for example, that the following causes an error:
```
→m
```

However, the equivalent works:
```
→M'
```

**Comment by NonstickAtom785** [comment]
Oh I thought I had just misread the documentation. I saw that you could use lowercase letters as vars but when I tried it gave me an error. So I assumed that it was a typo :P

**Comment by Zeda** [comment]
Fixed!
