### ISSUE TITLE
Reimplement ' option for Menu(

### ISSUE THREAD

**Issue by Zeda** [Zeda/Grammer2#19]
(Request from Hans description from Zeda)

`Menu(` used to have the (undocumented) option to leave a ' before an argument to set it as the default selection. For example:
```
Menu(0,0,48,"Title","OPT1",'"OPT2","EXIT

```

In that example, "OPT2" would be highlighted by default. When I rewrote the menu code, I removed that because it wasn't officially documented and it was going to be difficult to add in. It was, however, unofficially documented and it turns out that it is really useful.

**Comment by NonstickAtom785** [comment]
What's useful about it?

**Comment by Zeda** [comment]
As far as user interface goes, sometimes it is nice to save the users previous choice

**Comment by Zeda** [comment]
So it turned out, I remembered the syntax incorrectly. The correct syntax was where the option with the `'` is actually an expression that evaluates to the option number. Honestly, that makes way more sense. Anyways, it is fixed (again).
