### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by Zeda** [Zeda/Grammer2#20]
I'm starting a list of missing documentation, feel free to add to it:

- ~`]` command for parsing arguments~
- ~`?` a pointer to arguments for subroutines~
- ~`'` option for `Menu(`~
- ~`expr(` also parses `→` which can cause unexpected behavior.~

**Comment by NonstickAtom785** [comment]
Um there are token hooks for >dec and >frac. >lfactor and >Float. Was there a reason for that. I'm still on an outdated version of Grammer. Won't be updated till the 6th. I see we have a newcomer.

**Comment by Zeda** [comment]
`▶Dec`==>`▶Float` was from a while ago, documented [here](https://github.com/Zeda/Grammer2/blob/master/docs/math.md#floating-point). It basically takes a pointer to a string and converts it to a float. It is useful if you are using `Input` and want a floating-point input (the user can type `3` instead of requiring `3.0`, for example).
```
Input ▶Float→.Z
```

`▶Frac`==>`▶lFactor` is documented [here](https://github.com/Zeda/Grammer2/blob/master/docs/math.md#math) and is used to quickly get the largest factor of a number.
```
Text(0,0,96▶lFactor
```
That will print `48` and `θ'` will be `2`

**Comment by Zeda** [comment]
I documented the ones listed, so I'm going to close this. If there is missing documentation, feel free to re-open.
