### ISSUE TITLE
Fix the softlink issue with the single folder.

### ISSUE THREAD

**Issue by Zeda** [Zeda/Grammer2#26]
I thought I had replaced the softlink with the actual folder; apparently not. I'll have to fix this!

**Comment by NonstickAtom785** [comment]
I fixed it... Just accept the pull requests. I'll be uploading the compiled Grammer in the morning. When I get it compiled.

**Comment by Zeda** [comment]
Thanks! There were a few bugs with that one that I've fixed btw (including the one you thought would be there with the token hook; off-by-one error :P).
