### ISSUE TITLE
problem occurs when compiling

### ISSUE THREAD

**Issue by ghost** [Zeda/Grammer2#32]
HI, I'm an Ubuntu user. I'm having this message :
![grammer2problem](https://user-images.githubusercontent.com/55626406/71547669-24adcf00-29a3-11ea-8acb-e22f41c1c8c0.jpg)
Any idea, please ?

**Comment by Zeda** [comment]
It's an issue with spasm-ng, see [issue 53](https://github.com/alberthdev/spasm-ng/issues/53). alberthdev had made a fixed version, but I guess they haven't merged it yet, sorry:
https://github.com/alberthdev/spasm-ng/tree/feature/app-name-var-size

I'll update the Grammer documentation.

**Comment by ghost** [comment]
Ok, thanks , I'll have to uninstall my spasm-ng version, then...
I'm working on a fork of grammer2, but I can't check any improvement for now.
Anyway I'm about to pull a request, would you mind testing if it's okay or not?
