### ISSUE TITLE
expr( Issue

### ISSUE THREAD

**Issue by NonstickAtom785** [Zeda/Grammer2#35]
When you try to make a string with commands in it and `expr(` it more than one time it throws an error.

**Comment by Zeda** [comment]
I'm not replicating this, do you mind giving example code? I tried this:
```
:.0:Return
:"3+4→Z
:Text('0,0,expr(Z
:Text('6,0,expr(Z
:DispGraph
:Stop
```

**EDIT:** I must have messed this up; this definitely doesn't work.

**Comment by NonstickAtom785** [comment]
```
.0:Return
"Rect(X,Y,7,7→Z
expr(Z
expr(Z
DispGraph
Stop
```

**Comment by Zeda** [comment]
Oh wow, that is interesting. First of all, that's a clever trick. What is happening is `expr(` is also parsing the `→Z` portion. I don't think there is a good way around this as I definitely want to be able to use tokens like `→` and `:`.

A note should be made in the readme about this, and instead, try something like:
```
:.0:Return
:"Rect(X,Y,7,7
:→Z
:expr(Z
:expr(Z
:DispGraph
:Stop
```

**Comment by NonstickAtom785** [comment]
Ö. I didn't think to do that!
Oh and I also had tried using the `Return` to get the pointer to the string. That didn't work either.

**Comment by Zeda** [comment]
Now that this is better documented, I'm going to close this issue. Feel free to re-open it if you need to.
