### ISSUE TITLE
_Ans

### ISSUE THREAD

**Issue by NonstickAtom785** [Zeda/Grammer2#36]
The _i_maginary i is used to access OS variable. Since Ans can be a bunch of variables I ran into the issue of Ans becoming corrupted(I guess). In my Omnicalc Font Editor I had to use Ans store it to OP1 and use HL to draw a character using VPutMap. At the time my ans was a string and when I ran the program, wait here's the peice...
```
F→_i_Ans
AsmPrgm<my code>
```
So the F didn't store the value to Ans like it would in Basic when you just put F. It put the tokenized data of the value at the front of the string. When the assembly code was ran I got a garbled character. When I exited to home I typed Ans and it gave me a string where I found the old string overlapped at the beginning with the tokenized data of F. When I tried replicating the issue I recalled Ans and got a crash. Another time I just got a seemingly endless display of scrolling.

That when I decided to set Ans=0. F was then properly stored into Ans. So then I did the obvious and used assembly code...
```
bacall(Op1Set0)
bcall(_StoAns)
ret
```
So everytime I run it I get the desired result.

I think the issue is with not checking what type of data is already in the variable. It's either that or you didn't have the use of the OS Ans variable in mind when you made it.

**Comment by NonstickAtom785** [comment]
Also I would like a couple ideas on how to improve my asm code and make it more like how grammer operates. Like displaying the character directly to the graph screen. Atm I'm copying the graph screen to the home screen then using VPutMap then copying the screen to the graph.

**Comment by Zeda** [comment]
Hmm, I'll see what I can do to fix this.
As for the assembly code, it might help to know that Grammer passes the previous value in register `BC`, so you can bypass the storing-to-Ans part. You can also use `bcall(_VPutMap)` on the graph screen by using `set textWrite, (IY + sGrFlags)` (just be sure to reset the bit it afterwards). Note that you'll need to use a `DispGraph`.

So if `F` is the char, you can do:
```
F:AsmPrgm21580822D786FDCB32D6FDCB14FE79EF5E45FDCB14BEFDCB3296C9
```
You might have to tweak the very beginning `215808`, which is the coordinates (the `58` means 88 pixels over, the `08` means 8 pixels down).

**EDIT:** The assembly code is:
```
	ld hl,8*256+88
	ld (pencol),hl
	set fracDrawLFont, (IY + fontFlags)
	set textWrite, (IY + sGrFlags)
	ld a,c
	bcall(_VPutMap)
	res textWrite, (IY + sGrFlags)
	res fracDrawLFont, (IY + fontFlags)
   	ret
```

**Comment by NonstickAtom785** [comment]
This was exactly the information I was looking for! Thanks! I didn't know about the textWrite thing...

**Comment by Zeda** [comment]
You should definitely get ahold of `83psysroutines.pdf`. It is TI's official reference. I think on TI's website, they make you jump through hoops, so I can either send you a copy via Discord or you can download it here: https://archive.org/details/pdfy-UJfjMPdvGB444Am_
