### ISSUE TITLE
Archive/Un-Archiving Issues

### ISSUE THREAD

**Issue by NonstickAtom785** [Zeda/Grammer2#4]
`UnArchive`, causes a crash for some reason. I tried making code to Archive the appvar Gray in the Grey Draw program for Grammer 2 and Un-Archiving the variable upon program execution, but it crashes the calc. _Note: It doesn't crash the first time but the second time it does._

**Comment by Zeda** [comment]
I'm having trouble replicating it, so could you give me some code to replicate the error? (Not like a giant chunk of code, but closer to the bare minimum to replicate it!)

Thanks! For what it is worth, here is the code I used to try to replicate it:
```
:.0:Return
:"5MYVAR→V
:Send(100,V
:Archive V
:UnArchive V
:Stop
```

**Comment by NonstickAtom785** [comment]
That's weird. It only happens when I try it on big programs on things like Tetris and Grey. The `UnArchive` I use in Grey is right after `Return`. I use `UnArchive "UGray` and `Archive "UGray` right after the `Repeat`'s `End`.

**Comment by Zeda** [comment]
Okay, it turned out that `bcall(_Arc_Unarc)` was overwriting code in RAM that handled page swapping (Grammer is a 2-page app, so some routines are on different pages. In my example, it never needed to go on the other page).
