### ISSUE TITLE
Stupid Issue

### ISSUE THREAD

**Issue by NonstickAtom785** [Zeda/Grammer2#6]
Don't forget to change the version number in Grammer. And so you don't forget the main menu archiving messes up the screen.

**Comment by Zeda** [comment]
Fixed! It turned out to be that the spot I was storing pointers for the VAT was a place that got overwritten during archiving and unarchiving (specifically, iMathPtr#, since probably the OS calls InsertMem or DelMem). Anyways, I fixed that, so thanks!

**EDIT:** Oh, and I updated the version :P
