### ISSUE TITLE
Adding to previous coords Text( Routine

### ISSUE THREAD

**Issue by NonstickAtom785** [Zeda/Grammer2#8]
Code:
```
: .0:Return
: ClrDraw
: Text(°"Fix It Please! XD
: Text(+8,,"Adding X works...
: Text(+7,,"Adding Y doesn't work...
: Text(+7,+0,"Doesn't work for Y either...
: Stop
```
The effect is like a latter since I don't have a screenie it looks something like this:
```
Fix It Please! XD
                  Adding X works...
                                   Adding Y doesn't work...
                                                           Doesn't work for Y either...
```

**Comment by Zeda** [comment]
I'm not replicating this issue, sorry. The code seems to be working as it should. Remember, the first coordinate is Y, then X, so your +7 just puts it down 7 pixels and continues at the X coordinates (then wraps down a line when it reaches the edge of the screen).

**Comment by NonstickAtom785** [comment]
I realize that now. Thanks for guiding me along.

**Comment by Zeda** [comment]
No problem, thanks for reporting ^~^
