### ISSUE TITLE
Grayscale

### ISSUE THREAD

**Issue by NonstickAtom785** [Zeda/Grammer2#9]
The grayscale routine is very laggy now in prgmGRAY. Thought you might want to know that.

**Comment by Zeda** [comment]
What is the `prgmGRAY` that you are referring to? For reference, I tested prgmGRAYDRAW and it seems to be working well.

**Comment by NonstickAtom785** [comment]
It's the same one. I added a contrast routine and maybe that's what's bugging it up.

**Comment by NonstickAtom785** [comment]
The inserted code goes as follows:
```
Lbl ". ->V
Lbl "D -> U
Lbl "C -> G
```
```
ClrDraw:ClrDrawZ
call G
```
All the way at the end of the code:
```
.C
Contrast(min(39,max(0,C+getkey(10 -getkey(11->C
End
```

**Comment by Zeda** [comment]
~~Is `call G` a typo ?~~ And where is that located? In the inner loop?
**EDIT:** Nvm, I didn't read it correctly. Still interested in where it is located.

**Comment by NonstickAtom785** [comment]
It's in the main loop. That's why I put the `ClrDraw:ClrDrawZ` before the `call G`. The occurance only happens when the call is in 15 MHz mode. I add another piece of code to the program that allows me to press XTON to put the calc in 15 MHz mode and again to put it back on 6 MHz mode. I did it so that when I want a clear grayscale I can just use that to do it. But when I'm moving the cursor around in 15 MHz mode it slows it down significantly whereas in the other mode no slow down is noticeable. 

Here's the piece of code that I added to do my bidding:
```
If getKey(40
FullWriteB(0,48+! Pause 7
```
I was messing around and that seemed to work although I don't know how it does. I used the Write byte because it seemed suitable. Pause 7 is only there to give you the time to let go of the button. If you could think of an easier way to do it would you please tell me?

Here's a Pastbin of the entire code aside from the sub routines. You'll notice I added a lot while keeping some of the original code.
[Gray Draw | Modified](https://pastebin.com/52aYcjgK)

**Comment by Zeda** [comment]
Your loop is actually about 19.3% *faster* with the updated LCD update routine (I honesty thought it would be in the 1% range, so nice). But I did see that the mask rotation was different from the old version which might make it look "choppy" at the ~18FPS your code is currently getting. I just updated a new version that matches the old masking rotation, so hopefully it will look better.

Also, I have found that, even though it makes moving the cursor look choppy, putting a `Repeat getKey`...`End` around the DispGraph makes it look much cleaner when the cursor is still. 
```
...

call U
Repeat getKey
DispGraph
End
call U

...
```

**Comment by NonstickAtom785** [comment]
Thanks Zeda.

**Comment by NonstickAtom785** [comment]
Okay just realized that adding both the `call U`'s into `Repeat getkey` as well as the one contrast subroutine `call G` will make the Grayscale smoother. Do you know why this would happen? It almost makes me think that the Greyscale routine was going so fast it started creating a pattern. Like when you look at a fan and it's on the highest speed. But I don't think that's possible. That's why I'm bringing it up and opening this discussion again. Also when you change drawing method to line it also make it smoother (even more if you make it smaller.)

Code Block:
```
Repeat getkey
call U
DispGraph
call U
call G
End
```

The one with the pattern effect it just the `Repeat getKey` and `DispGraph` followed by an `End`.

**Comment by Zeda** [comment]
Drawing the shapes is relatively slow, so the bigger they are, the more they'll lag (which is why I suggested keeping it out of the loop). Does the pattern look like diagonal lines (45°) or does it look somewhat jagged? That can happen if the loop manages to refresh at just the perfect speed (like resonance; refreshing at some specific multiple of the LCDs refresh rate). Maybe keep the drawing calls outside the loop, but keep your contrast routine in the loop?
